#!/usr/bin/env bash

set -eu

# Install Homebrew if not already installed
if ! command -v brew &> /dev/null; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    echo "Homebrew already installed"
fi

# Update Homebrew
brew update

packages="gdb git-delta curl neovim tree-sitter-cli tmux fzf fd-find ripgrep yt-dlp clang tree"

for package in $packages; do
    if brew list "$package" &>/dev/null; then
        echo "$package already installed" -n "running $script..."
    else
        echo -n "installing $package..."
        brew install "$package"
        echo "done."
    fi
done
