#!/usr/bin/env bash

set -eu

if ! command -v git &> /dev/null; then
    echo "Installing git..."
    case "$OSTYPE" in
        linux-gnu*)
            sudo apt-get install -y git
            ;;
        darwin*)
            if ! command -v brew &> /dev/null; then
                echo "Installing Homebrew..."
                /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
                export PATH="$HOMEBREW_PATH:$PATH"
            else
                echo "Homebrew already installed"
            fi

            brew install git
            echo ".DS_Store" >> ~/.gitignore_global
            git config --global core.excludesfile ~/.gitignore_global
            ;;
        *)
            printf 'Unsupported platform: "$OSTYPE"' >&2; exit 1 ;;
    esac
fi

REPO_URL="https://github.com/ianebeckett/dev"
REPO_DIR="$HOME/dev"

if [ ! -d "$REPO_DIR/.git" ]; then
    echo "Cloning dev to $REPO_DIR..."
    git clone "$REPO_URL" "$REPO_DIR"
else
    echo "dev already exists at $REPO_DIR"
fi

cd "$REPO_DIR"

echo "Updating dev..."
git pull

echo "Running configuration scripts..."
"$REPO_DIR/runner"

echo "Setup complete!"
