#!/usr/bin/env bash
sudo apt -y update

if ! command -v git &> /dev/null; then
    sudo apt -y install git
fi

ln -s "$HOME/dev/env/.gitconfig" "$HOME/.gitconfig"

if [ ! -d $HOME/dev]; then
    mkdir $HOME/dev
fi

git clone https://github.com//dev https://github.com/ianedwardbeckett/dev $HOME/dev
# TODO: set up ssh key

./run
