#!/usr/bin/env bash

# I'm allowing indirection by following symlinks to make this a "jump almost
# anywhere" script instead of a "jump into my dev env" script.

DIRS=(
    $HOME
    $HOME/personal
    $HOME/.config
    $HOME/.local
    $HOME/school
    $HOME/school/*
    $HOME/work
)

if [[ $# -eq 1 ]]; then
    selected=(realpath $1) 
else
    selected=$(
        find -L "${DIRS[@]}" -mindepth 1 -maxdepth 1 -type d \
        | sed "s|^$HOME/||" \
        | fzf --layout=reverse
    )
fi

if [[ -z $selected ]]; then
    exit 0
fi

selectedName=$(basename "$selected" | tr ".,: " "____")
tmuxRunning=$(pgrep tmux)

# not running
if [[ -z $tmuxRunning ]]; then
    tmux new-session -s $selectedName -c $selected
    exit 0
fi

# detached
if [[ -z $TMUX ]]; then
    tmux new-session -A -s $selectedName -c $selected
fi

# attached
if ! tmux has-session -t=$selectedName 2> /dev/null; then
    tmux new-session -ds $selectedName -c $selected
fi

tmux switch-client -t $selectedName

