#!/usr/bin/env bash

DIRS=(
    $HOME/personal
    $HOME/school
    $HOME/work
)

selected=$(
    printf "%s\n" "${DIRS[@]}" \
    | sed "s|^$HOME/||" \
    | fzf --layout=reverse
)

if [[ -z $selected ]]; then
    exit 0
fi

nvim $HOME/"$selected"/todo.md
exit 0
