#!/usr/bin/env bash

set -eu

source "$HOME/dev/lib/links.sh"

link_config "$HOME/dev/env/.config/agents" "$XDG_CONFIG_HOME/agents"
link_config "$HOME/dev/env/.config/agents/AGENTS.md" "$XDG_CONFIG_HOME/opencode/AGENTS.md"
link_config "$HOME/dev/env/.config/agents/AGENTS.md" "$HOME/.codex/AGENTS.md"
link_config "$HOME/dev/env/.config/agents/AGENTS.md" "$HOME/.claude/CLAUDE.md"
