#!/usr/bin/env bash

set -eu

if [[ "$OSTYPE" == "darwin"* ]]; then
    "$HOME/dev/runs/install/macos"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    "$HOME/dev/runs/install/linux"
else
    echo "Unsupported OS: $OSTYPE"
    exit 1
fi
