#!/usr/bin/env bash

set -eu

packages="gdb git-delta curl neovim tree-sitter-cli tmux fzf fd-find ripgrep yt-dlp clang tree trash-cli"

case "$OSTYPE" in
    linux-gnu*)

        packages+=" zsh"

        echo "upgrading apt packages..."
        sudo apt-get update
        sudo apt-get upgrade

        # Disable apport (Ubuntu crash reporting)
        sudo sed -i 's/enabled=1/enabled=0/g' /etc/default/apport

        echo "installing packages..."
        for package in $packages; do
            echo -n "$package:"
            if dpkg -s "$package" &>/dev/null; then
                echo " already installed"
            else
                sudo apt-get install "$package"
            fi
        done
        ;;

    darwin*)

        if ! command -v brew &> /dev/null; then
            echo "Installing Homebrew..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        else
            echo "Homebrew already installed"
        fi

        brew update

        for package in $packages; do
            if brew list "$package" &>/dev/null; then
                echo "$package already installed"
            else
                brew install "$package"
            fi
        done
        ;;

    *)
        printf 'Unsupported platform: %s\n' "$OSTYPE" >&2; exit 1 ;;
esac
