#!/usr/bin/env bash

set -e

# Install Homebrew if not already installed
if ! command -v brew &> /dev/null; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    echo "Homebrew already installed"
fi

# Update Homebrew
brew update

packages="gdb git curl neovim tmux fzf ripgrep yt-dlp clang tree"

for package in $packages; do
    if brew list "$package" &>/dev/null; then
        echo "$package already installed"
    else
        brew install "$package"
    fi
done
