#!/usr/bin/env bash

git clone -b release-0.12 git@github.com:neovim/neovim.git $HOME/.local/neovim
sudo apt install cmake gettext lua5.1 liblua5.1.0-dev #etc

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
